### ISSUE TITLE
chance.unique not so unique when generating dates with options

### ISSUE THREAD

**Issue by izeau** [chancejs/chancejs#246]
Hi guys,

I need to generate some unique dates within a range but chance.unique does not seem to work when using chance.date:

```
chance.unique(chance.date, 4, { year: 2016 });

// [ Mon Sep 22 2016 06:55:03 GMT+0200 (CEST),
//   Mon Sep 22 2016 06:55:03 GMT+0200 (CEST),
//   Mon Sep 22 2016 06:55:03 GMT+0200 (CEST),
//   Mon Sep 22 2016 06:55:03 GMT+0200 (CEST) ]
```

If I don’t specify the `{ year: 2016 }` option, dates appear to be unique though.

**Comment by akre54** [comment]
That's because chance mutates the passed-in `options` object, so the first time around it sets `day`, `hour`, `minutes`, etc to the options object, and the second time it won't fill in the defaults because the object isn't empty. If you don't add in the `options` argument, `initOptions` will supply one for you, and that `unique` uses `.apply` instead of `call`, which doesn't allow `options` to be reassigned. 

This is definitely a bug.

The simple solution is to clone/extend the `params` object in `unique`.

**Comment by akre54** [comment]
bump @victorquinn

**Comment by victorquinn** [comment]
Yup, totally a problem, working on a fix now!

**Comment by victorquinn** [comment]
Also, one of these days I am going to update Chance to never mutate the supplied options object, that was a terribly messy mistake.
