### ISSUE TITLE
Repeating Characters 

### ISSUE THREAD

**Issue by spencerthayer** [chancejs/chancejs#325]
In a `chance.string` is there an option to ensure that there are never any repeating characters in the output?

**Comment by victorquinn** [comment]
nope, not at current, that would be a nice addition!

**Comment by spencerthayer** [comment]
So the problem I have so far is that I don't get the total 16 characters specified in the params of `chanceString` when there are dupes. Example below:

```javascript
      function uniqueArray(array) {
          return array.filter(function(itm, i, T) {
              return T.indexOf(itm) == i;
          });
      }
      var noUnique = uniqueArray(chanceString.split('')).join('')
      console.log("Pass: " + chanceString); //0B!@+-lHBJ0ZNFuG
      console.log("Uniq: " + noUnique);     //0B!@+-lHJZNFuG
```

**Comment by spencerthayer** [comment]
Incidentally, I am bugging you so much because when I found chance.js I realized it was the perfect solution to improving my stateless password generating app https://github.com/spencerthayer/Passcloud. So I'm rebuilding it entirely around chance.js.

**Comment by spencerthayer** [comment]
Any thoughts on how to do this?

**Comment by victorquinn** [comment]
Hey @spencerthayer apologies on the long response here! And very cool to hear about using it for the password generation. 

So yes there are a couple ways to accomplish this. First, we should probably add a feature to the `string()` method which would enable no repeats. (will add it shortly!)

However, before that exists, one way to accomplish what you want with what exists today would be to use the `unique` method to generate N unique characters, then join them together as a string.

For example:

```js
function uniqueString(len) {
  return chance.unique(chance.character, len).join('');
}
// Will generate len unique characters and join them together as a string
```

Note, this is a bit more aggressive than you're actually looking for as it ensures no characters are duplicated throughout the whole string, not just next to each other, but it should work.

Will add the "no repeat" flag to `string()` in the near future though because that seems very useful!

**Comment by spencerthayer** [comment]
This is exactly what I am looking for. Something that generates unique strings throughout the password. However, when I give it a pool it seems to cause a problem.

```javascript
function uniqueString(len) {
            return chanceHash.unique(
                chance.character({ pool: "abcdef%^&" }), len
            ).join('');
        }
```

```error
RangeError: Chance: The first argument must be a function. chance.min.js:1:721
```

**Comment by victorquinn** [comment]
Yes @spencerthayer that is because `chance.unique` expects a function as its first argument and you supplied a string (`chance.character()` with a pool will return a single character as a string).

Instead, to call it with a known pool, you would do this:

```js
// Return a string of all unique characters, selected from the provided pool
function uniqueString(len) {
    return chance.unique(chance.character, len, { pool: "abcdef%^&" }).join('')
}
// then call it
> uniqueString(6)
"dc%^e&"
```
_Note in the above implementation, since the pool is only 9 characters long, that is the maximum length of the string you could generate with all unique characters from that pool. Chance will throw a `RangeError` if you try to provide a larger number than the function could generate._

Also worth noting I just realized the docs for `chance.unique()` don't adequately convey that any params you'd like to pass to the called function come at the end so I'll fix that.

**Comment by spencerthayer** [comment]
Dude! Thank you so much! This script now produces super strong passwords when I provide a poolString like `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*_-=+`~()[]{};:'",.<>?/\|¡¢£¤¥¦§¨©ª®°±µ¿`. But more importantly, the user can select the characters they want programmatically and never get a repeating character.

```javascript
if (passType == "password") {
        function uniqueString(len) {
            return chance.unique(chance.character, len, { pool: poolString }).join('')
        }
        domainPassword = uniqueString(charLength);
    }
```

**Comment by spencerthayer** [comment]
I do look forward to seeing what you do with String and maybe making it more efficient but this is totally closed in my book.
